  version: '2'

  services:
    db:
      image: mysql:5.7
      ports:
        - 3307:3306
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
      build:
        context: php7-fpm
        args:
          TIMEZONE: ${TIMEZONE}
      volumes:
        - ${SYMFONY_APP_PATH}:/var/www/symfony
      environment:
        - SSH_AUTH_SOCK
    nginx:
      build: nginx
      ports:
        - 8080:80
      volumes_from:
        - php
      volumes:
        - ./logs/nginx/:/var/log/nginx
